name: main
on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm ls
      - run: ./node_modules/.bin/eslint ./
      - run: ./node_modules/.bin/stylelint ./**/*.css ./**/*.html ./**/*.js
